criterion: MSELoss
dataloader_params:
  batch_size: 5
  shuffle: true
dataset_params:
  conn_string: postgresql://postgres:12345@localhost:5432/FlightDB
  data_query: select fid, packet, tele_altitude from slow_params
  label_query: "\n                        select fid, exists(select 1 from slow_params\
    \ sp2 where tele_altitude > 10000 and sp2.fid = sp.fid)\n                    \
    \    from slow_params sp\n                        group by fid\n             \
    \         "
  pool_func: avg
  samples_per_flight: 1000
model: LSTM
model_params:
  hidden_size: 32
  input_size: 3
  num_layers: 2
  proj_size: 2
num_epochs: 10
optimizer: Adam
optimizer_params:
  lr: 0.001
  weight_decay: 0.0005
path: models/test.pt
seed: 42
split_params:
- 0.6
- 0.2
- 0.2
